/*
 * Generated by Bluespec Compiler, version 2017.03.beta1 (build 35049, 2017-03-16)
 * 
 * On Thu Apr 19 13:13:52 IST 2018
 * 
 */

/* Generation options: */
#ifndef __mkTB_h__
#define __mkTB_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkStage.h"


/* Class declaration for the mkTB module */
class MOD_mkTB : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_c0;
  MOD_Reg<tUInt32> INST_c1;
  MOD_Reg<tUInt32> INST_clk;
  MOD_mkStage INST_cnnR;
  MOD_Reg<tUInt32> INST_cols;
  MOD_Reg<tUInt8> INST_flagg;
  MOD_Reg<tUInt8> INST_init;
  MOD_Reg<tUInt32> INST_rows;
  MOD_Reg<tUInt32> INST_test_reg;
 
 /* Constructor */
 public:
  MOD_mkTB(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt32 DEF_b__h388;
 
 /* Local definitions */
 private:
  tUWide DEF_cnnR_receive___d41;
 
 /* Rules */
 public:
  void RL_init_rule();
  void RL_update_clock();
  void RL_layerIn();
  void RL_layerOut();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTB &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTB &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTB &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTB &backing);
};

#endif /* ifndef __mkTB_h__ */
