webtalk_init -webtalk_dir /home/csgvinamra/Board/FlowCNN/src/FCLayer/xsim.dir/ver.xsim/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 30 16:07:00 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1215546" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211375316_0_0_603" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "41de3f68-cc49-4482-a46e-6286657ff545" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8674f320-242e-4723-bd30-1d4c4c0cda94" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU           W3550  @ 3.07GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2819.274 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "11" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "4717 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "1891 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "84464" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "57476" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "2574" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "71.65_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "743344_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2286624574 -regid "211375316_0_0_603" -xml /home/csgvinamra/Board/FlowCNN/src/FCLayer/xsim.dir/ver.xsim/webtalk/usage_statistics_ext_xsim.xml -html /home/csgvinamra/Board/FlowCNN/src/FCLayer/xsim.dir/ver.xsim/webtalk/usage_statistics_ext_xsim.html -wdm /home/csgvinamra/Board/FlowCNN/src/FCLayer/xsim.dir/ver.xsim/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
